# Database credentials
readerDatabase:
  user: "agora"
  name: "db"
  host: "host.docker.internal"
  port: "5432"
  password: "12345678"
writerDatabase:
  user: "agora"
  name: "db"
  host: "host.docker.internal"
  port: "5432"
  password: "12345678"

# Chain network configuration
chain:
  configPath: /config/chain-config-capella.yaml
  genesisTimestamp: REPLACE_GENESIS_TIME_STAMP

# Note: It is possible to run either the frontend or the indexer or both at the same time
# Frontend config
frontend:
  enabled: true # Enable or disable to web frontend
  imprint: "templates/imprint.example.html"  # Path to the imprint page content
  siteName: "Explorer" # Name of the site, displayed in the title tag
  siteSubtitle: "Explorer" # Subtitle shown on the main page
  csrfAuthKey: '0123456789abcdef000000000000000000000000000000000000000000000000'
  jwtSigningSecret: "0123456789abcdef000000000000000000000000000000000000000000000000"
  jwtIssuer: "localblockexplorer"
  jwtValidityInMinutes: 30
  server:
    host: "0.0.0.0" # Address to listen on
    port: "3333" # Port to listen on
  readerDatabase:
    user: "agora"
    name: "db"
    host: "host.docker.internal"
    port: "5432"
    password: "12345678"
  writerDatabase:
    user: "agora"
    name: "db"
    host: "host.docker.internal"
    port: "5432"
    password: "12345678"
  sessionSecret: "a05b7224e46c2a02bf933fff596a35367c8355ba20b95704f7e1edc524d1c913"
  email:
    smtp:
      server: "<emailserver>"
      host: "<emailhost>"
      user: "<emailuser>"
      password: "<emailpassword>"
  flashSecret: "" # Encryption secret for flash cookies

# Indexer config
indexer:
  enabled: true # Enable or disable the indexing service
  fullIndexOnStartup: false # Perform a one time full db index on startup
  indexMissingEpochsOnStartup: false # Check for missing epochs and export them after startup
  node:
    host: "host.docker.internal" # Address of the backend node
    port: "3500"
    grpcPort: "4000"
    type: "prysm"
    pageSize: 500
  eth1Endpoint: "/el/geth.ipc"
  eth1DepositContractAddress: "0x4Ca91738C7cD24895467c6d550D96BE8dC4b33AA"
  eth1DepositContractFirstBlock: 8
