version: '3.3'
services:
  elboot:
    container_name: elboot
    image: bosagora/agora-el-bootnode:v1.0.1
    restart: always
    volumes:
      - ../config/el:/config
    command:
      -nodekey=/config/bootkey/boot.key
      -verbosity=1
      -addr=:30301
    networks:
      default_network:
        ipv4_address: 172.200.0.11

  clboot:
    container_name: clboot
    image: bosagora/agora-cl-bootnode:v1.0.3
    restart: always
    command:
      --external-ip 172.200.0.12
      --fork-version 2F1C0000
      --private 9dab6d31b7fd636348b29c8c0c8ee3699e1f89bfe06e62c795821156040b969e
    networks:
      default_network:
        ipv4_address: 172.200.0.12

  node1-1-el:
    container_name: node1-1-el
    image: bosagora/agora-el-node:v1.0.1
    ports:
      - "8545:8545"
    restart: always
    volumes:
      - ../chain/node1/el:/data
      - ../config/el:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --allow-insecure-unlock=true
      --unlock=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xF85B2dbA83A08DEe6E24E4461E0334e7384896F9
    networks:
      default_network:
        ipv4_address: 172.200.0.21
    depends_on:
      - elboot

  node1-2-cl:
    container_name: node1-2-cl
    image: bosagora/agora-cl-node:v1.0.3
    ports:
      - "3500:3500"
      - "4000:4000"
    volumes:
      - ../chain/node1/cl:/cl
      - ../chain/node1/el:/el
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --config-file=/config/config.yaml
      --datadir=/cl
      --execution-endpoint=/el/geth.ipc
      --contract-deployment-block=8
      --accept-terms-of-use
      --subscribe-all-subnets=true
      --disable-peer-scorer=true
      --enable-debug-rpc-endpoints=true
    networks:
      default_network:
        ipv4_address: 172.200.0.22
    depends_on:
      - clboot
      - node1-1-el

  node1-3-val:
    container_name: node1-3-val
    image: bosagora/agora-cl-validator:v1.0.3
    volumes:
      - ../chain/node1/cl:/cl
      - ../wallet/val1:/wallet
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --datadir=/cl
      --beacon-rpc-gateway-provider=node1-2-cl:3500
      --beacon-rpc-provider=node1-2-cl:4000
      --wallet-dir=/wallet
      --proposer-settings-file=/config/private/proposer_config.json
      --wallet-password-file=/config/private/password.txt
      --accept-terms-of-use
    networks:
      default_network:
        ipv4_address: 172.200.0.23
    depends_on:
      - node1-2-cl

  node2-1-el:
    container_name: node2-1-el
    image: bosagora/agora-el-node:v1.0.1
    restart: always
    volumes:
      - ../chain/node2/el:/data
      - ../config/el:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --allow-insecure-unlock=true
      --unlock=0x93BFD12E0050B16D69f752dfd344Ebd174bd3159
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0x93BFD12E0050B16D69f752dfd344Ebd174bd3159
    networks:
      default_network:
        ipv4_address: 172.200.0.31
    depends_on:
      - elboot
      - node1-1-el

  node2-2-cl:
    container_name: node2-2-cl
    image: bosagora/agora-cl-node:v1.0.3
    volumes:
      - ../chain/node2/cl:/cl
      - ../chain/node2/el:/el
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --config-file=/config/config.yaml
      --datadir=/cl
      --execution-endpoint=/el/geth.ipc
      --contract-deployment-block=8
      --accept-terms-of-use
      --subscribe-all-subnets=true
      --disable-peer-scorer=true
    networks:
      default_network:
        ipv4_address: 172.200.0.32
    depends_on:
      - clboot
      - node2-1-el

  node2-3-val:
    container_name: node2-3-val
    image: bosagora/agora-cl-validator:v1.0.3
    volumes:
      - ../chain/node2/cl:/cl
      - ../wallet/val2:/wallet
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --datadir=/cl
      --beacon-rpc-gateway-provider=node2-2-cl:3500
      --beacon-rpc-provider=node2-2-cl:4000
      --wallet-dir=/wallet
      --proposer-settings-file=/config/private/proposer_config.json
      --wallet-password-file=/config/private/password.txt
      --accept-terms-of-use
    networks:
      default_network:
        ipv4_address: 172.200.0.33
    depends_on:
      - node2-2-cl

  node3-1-el:
    container_name: node3-1-el
    image: bosagora/agora-el-node:v1.0.1
    restart: always
    volumes:
      - ../chain/node3/el:/data
      - ../config/el:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --allow-insecure-unlock=true
      --unlock=0xb7D44Dc8cbC8119552608E5AB4E9e59a6120Ccf0
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xb7D44Dc8cbC8119552608E5AB4E9e59a6120Ccf0
    networks:
      default_network:
        ipv4_address: 172.200.0.41
    depends_on:
      - elboot
      - node1-1-el
      - node2-1-el

  node3-2-cl:
    container_name: node3-2-cl
    image: bosagora/agora-cl-node:v1.0.3
    volumes:
      - ../chain/node3/cl:/cl
      - ../chain/node3/el:/el
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --config-file=/config/config.yaml
      --datadir=/cl
      --execution-endpoint=/el/geth.ipc
      --contract-deployment-block=8
      --accept-terms-of-use
      --subscribe-all-subnets=true
      --disable-peer-scorer=true
    networks:
      default_network:
        ipv4_address: 172.200.0.42
    depends_on:
      - clboot
      - node3-1-el

  node3-3-val:
    container_name: node3-3-val
    image: bosagora/agora-cl-validator:v1.0.3
    volumes:
      - ../chain/node3/cl:/cl
      - ../wallet/val3:/wallet
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-bellatrix.yaml
      --datadir=/cl
      --beacon-rpc-gateway-provider=node3-2-cl:3500
      --beacon-rpc-provider=node2-2-cl:4000
      --wallet-dir=/wallet
      --proposer-settings-file=/config/private/proposer_config.json
      --wallet-password-file=/config/private/password.txt
      --accept-terms-of-use
    networks:
      default_network:
        ipv4_address: 172.200.0.43
    depends_on:
      - node3-2-cl

  node4-1-el:
    container_name: node4-1-el
    image: bosagora/agora-el-node:v1.0.2
    restart: always
    volumes:
      - ../chain/node4/el:/data
      - ../config/el:/config
    command:
      --config=/config/config.toml
      --datadir=/data
      --syncmode=full
      --allow-insecure-unlock=true
      --unlock=0xF051b6ed4cd4D1De4810833048776F835F3c266D
      --password=/config/private/password.txt
      --mine=true
      --miner.etherbase=0xF051b6ed4cd4D1De4810833048776F835F3c266D
    networks:
      default_network:
        ipv4_address: 172.200.0.51
    depends_on:
      - elboot
      - node1-1-el
      - node2-1-el
      - node3-1-el

  node4-2-cl:
    container_name: node4-2-cl
    image: bosagora/agora-cl-node:agora-v4.0.3
    volumes:
      - ../chain/node4/cl:/cl
      - ../chain/node4/el:/el
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-capella.yaml
      --config-file=/config/config.yaml
      --datadir=/cl
      --execution-endpoint=/el/geth.ipc
      --contract-deployment-block=8
      --accept-terms-of-use
      --subscribe-all-subnets=true
      --disable-peer-scorer=true
    networks:
      default_network:
        ipv4_address: 172.200.0.52
    depends_on:
      - clboot
      - node4-1-el

  node4-3-val:
    container_name: node4-3-val
    image: bosagora/agora-cl-validator:agora-v4.0.3
    volumes:
      - ../chain/node4/cl:/cl
      - ../wallet/val4:/wallet
      - ../config/cl:/config
    restart: always
    command:
      --chain-config-file=/config/chain-config-capella.yaml
      --datadir=/cl
      --beacon-rpc-gateway-provider=node4-2-cl:3500
      --beacon-rpc-provider=node4-2-cl:4000
      --wallet-dir=/wallet
      --proposer-settings-file=/config/private/proposer_config.json
      --wallet-password-file=/config/private/password.txt
      --accept-terms-of-use
    networks:
      default_network:
        ipv4_address: 172.200.0.53
    depends_on:
      - node4-2-cl

networks:
  default_network:
    ipam:
      driver: default
      config:
        - subnet: 172.200.0.0/16

volumes:
  bazel-cache:
